server:
  port: 8387

# Oracle connect
spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger

  # JPA Setting
  jpa:
     show-sql: true
     hibernate:
       ddl-auto: none
#       이 설정은 Hibernate가 데이터베이스 
#       스키마를 자동으로 생성 또는 업데이트하지 않도록 합니다.
        
    #view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
      #gmail설정 vpsm tsck csal aqvt
  mail:
    host: smtp.gmail.com
    port: 587
    username: wjdtod12ahdl@gmail.com
    password: vpsm tsck csal aqvt
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
      
      
  #mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
  
logging.level:
  org.hibernate.SQL: debug  #logger를 통해 하이버네이트 실행 SQL